services:
  freeradius:
    build:
      context: ./freeradius
    container_name: freeradius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    networks:
      - captive_net
    restart: unless-stopped

networks:
  captive_net:
    external: true
